### PR TITLE
Test deprovision via VM

### PR DESCRIPTION
**Pull request by mmlb**
## Description

This PR adds deprovision to the vm based test, along with preparations for
another PR I will open that adds booting the VM and checking for phone-home.

## Why is this needed

Deprovision isn't currently tested.

## How Has This Been Tested?

Qemu based tests in ci/vm.sh

### CODE REVIEW

**Review by splaspood — DISMISSED** [review]

**Review by markjacksonfishing — DISMISSED** [review]
Do we squash? I think this should be

**Comment by mmlb** [comment]
> Do we squash? I think this should be

Never!

**Comment by mmlb** [comment]
Rebased and forced push to fix a typo (virtion-net) in a commit message and fixed the shellcheck warnings.

**Review by markjacksonfishing — DISMISSED** [review]

**Comment by mmlb** [comment]
I've got a boot test that I'm trying to add to this PR, its expected to fail for now (follow up PR will fix) but its just hanging. So I'm debugging that.

**Comment by mmlb** [comment]
> I've got a boot test that I'm trying to add to this PR, its expected to fail for now (follow up PR will fix) but its just hanging. So I'm debugging that.

NM, I'll do that in a different PR.

**Review by markjacksonfishing — APPROVED** [review]
hey, I just reviewed this.
And this is crazy,
but here's my hogwash,
so squash this maybe

**Pull request merged**
