### PR TITLE
Update ascii art branding

### PR DESCRIPTION
**Pull request by dlaube**
## Description

This updates Equinix Metal rebranding for rescueOS.

## How Has This Been Tested?
DroneCI automated testing

## How are existing users impacted? What migration steps/scripts do we need?
NA

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Review by dustinmiller — APPROVED** [review]
Awesome 🎉

**Comment by mmlb** [comment]
I kind of find it harder to read than the Packet one. Maybe a different "font"?

**Comment by mmlb** [comment]
Some more legible options?:

http://patorjk.com/software/taag/#p=display&f=3D-ASCII&t=Equinix
```
 _______   ________  ___  ___  ___  ________   ___     ___    ___ 
|\  ___ \ |\   __  \|\  \|\  \|\  \|\   ___  \|\  \   |\  \  /  /|
\ \   __/|\ \  \|\  \ \  \\\  \ \  \ \  \\ \  \ \  \  \ \  \/  / /
 \ \  \_|/_\ \  \\\  \ \  \\\  \ \  \ \  \\ \  \ \  \  \ \    / / 
  \ \  \_|\ \ \  \\\  \ \  \\\  \ \  \ \  \\ \  \ \  \  /     \/  
   \ \_______\ \_____  \ \_______\ \__\ \__\\ \__\ \__\/  /\   \  
    \|_______|\|___| \__\|_______|\|__|\|__| \|__|\|__/__/ /\ __\ 
                    \|__|                             |__|/ \|__| 
```

http://patorjk.com/software/taag/#p=display&f=Alpha&t=Equinix
```


          _____                   _______                   _____                    _____                    _____                    _____                                  
         /\    \                 /::\    \                 /\    \                  /\    \                  /\    \                  /\    \                 ______          
        /::\    \               /::::\    \               /::\____\                /::\    \                /::\____\                /::\    \               |::|   |         
       /::::\    \             /::::::\    \             /:::/    /                \:::\    \              /::::|   |                \:::\    \              |::|   |         
      /::::::\    \           /::::::::\    \           /:::/    /                  \:::\    \            /:::::|   |                 \:::\    \             |::|   |         
     /:::/\:::\    \         /:::/~~\:::\    \         /:::/    /                    \:::\    \          /::::::|   |                  \:::\    \            |::|   |         
    /:::/__\:::\    \       /:::/    \:::\    \       /:::/    /                      \:::\    \        /:::/|::|   |                   \:::\    \           |::|   |         
   /::::\   \:::\    \     /:::/    / \:::\    \     /:::/    /                       /::::\    \      /:::/ |::|   |                   /::::\    \          |::|   |         
  /::::::\   \:::\    \   /:::/____/   \:::\____\   /:::/    /      _____    ____    /::::::\    \    /:::/  |::|   | _____    ____    /::::::\    \         |::|   |         
 /:::/\:::\   \:::\    \ |:::|    |     |:::|    | /:::/____/      /\    \  /\   \  /:::/\:::\    \  /:::/   |::|   |/\    \  /\   \  /:::/\:::\    \  ______|::|___|___ ____ 
/:::/__\:::\   \:::\____\|:::|____|     |:::|____||:::|    /      /::\____\/::\   \/:::/  \:::\____\/:: /    |::|   /::\____\/::\   \/:::/  \:::\____\|:::::::::::::::::|    |
\:::\   \:::\   \::/    / \:::\   _\___/:::/    / |:::|____\     /:::/    /\:::\  /:::/    \::/    /\::/    /|::|  /:::/    /\:::\  /:::/    \::/    /|:::::::::::::::::|____|
 \:::\   \:::\   \/____/   \:::\ |::| /:::/    /   \:::\    \   /:::/    /  \:::\/:::/    / \/____/  \/____/ |::| /:::/    /  \:::\/:::/    / \/____/  ~~~~~~|::|~~~|~~~      
  \:::\   \:::\    \        \:::\|::|/:::/    /     \:::\    \ /:::/    /    \::::::/    /                   |::|/:::/    /    \::::::/    /                 |::|   |         
   \:::\   \:::\____\        \::::::::::/    /       \:::\    /:::/    /      \::::/____/                    |::::::/    /      \::::/____/                  |::|   |         
    \:::\   \::/    /         \::::::::/    /         \:::\__/:::/    /        \:::\    \                    |:::::/    /        \:::\    \                  |::|   |         
     \:::\   \/____/           \::::::/    /           \::::::::/    /          \:::\    \                   |::::/    /          \:::\    \                 |::|   |         
      \:::\    \                \::::/____/             \::::::/    /            \:::\    \                  /:::/    /            \:::\    \                |::|   |         
       \:::\____\                |::|    |               \::::/    /              \:::\____\                /:::/    /              \:::\____\               |::|   |         
        \::/    /                |::|____|                \::/____/                \::/    /                \::/    /                \::/    /               |::|___|         
         \/____/                  ~~                       ~~                       \/____/                  \/____/                  \/____/                 ~~              
                                                                                                                                                                              
```

http://patorjk.com/software/taag/#p=display&f=Ivrit&t=Equinix
```
  _____            _       _      
 | ____|__ _ _   _(_)_ __ (_)_  __
 |  _| / _` | | | | | '_ \| \ \/ /
 | |__| (_| | |_| | | | | | |>  < 
 |_____\__, |\__,_|_|_| |_|_/_/\_\
          |_|                     
```

http://patorjk.com/software/taag/#p=display&f=Big&t=Equinix
```
  ______            _       _      
 |  ____|          (_)     (_)     
 | |__   __ _ _   _ _ _ __  ___  __
 |  __| / _` | | | | | '_ \| \ \/ /
 | |___| (_| | |_| | | | | | |>  < 
 |______\__, |\__,_|_|_| |_|_/_/\_\
           | |                     
           |_|                     
```

**Comment by mmlb** [comment]
Actually nm it looks better in the terminal than in Github ui.

**Comment by thebsdbox** [comment]
Out of interest given that we previously removed a lot of references to "packet" in some earlier PRs as the plan is to make this agnostic and community driven. Does it make sense to keep this here?

-> https://github.com/tinkerbell/tink/pull/255

**Comment by dlaube** [comment]
> Out of interest given that we previously removed a lot of references to "packet" in some earlier PRs as the plan is to make this agnostic and community driven. Does it make sense to keep this here?
> 

Yes, because this is removing Packet and replacing it with Equinix for today's rebranding. If we want to decide to remove it at a later date, that's fine by me.

**Pull request merged**
