### PR TITLE
Help osie talk to s3

### PR DESCRIPTION
**Pull request by andy-v-h**
## Description

Setting OSIE up to be able to talk to S3 interface

## Why is this needed

We intend on migrate packet-images to S3

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Review by mikemrm — DISMISSED** [review]
I think this looks good. Though I think it would also be nice to be able to specify a different s3 host / endpoint as well.

**Comment by andy-v-h** [comment]
> I think this looks good. Though I think it would also be nice to be able to specify a different s3 host / endpoint as well.

Yes. Just verifying functionality, will move to Ceph Object store eventually do be in each facility

**Review by markjacksonfishing — DISMISSED** [review]

**Comment by andy-v-h** [comment]
Tested two ubuntu deployments on x1.small.x86 nodes with userdata like 

```
#cloud-config
#services={"osie":"aholtzmann-s3-2"}
#image_uri=https://artifacts.edge-a.ewr1.metalkube.net/images/x86_64/ubuntu/20_04
```
and
```
#cloud-config
#services={"osie":"aholtzmann-s3-2"}
```

I still want to wait for https://github.com/tinkerbell/osie/pull/219 to be merged since that fixes a breaking change

**Review by markjacksonfishing — APPROVED** [review]

**Comment by andy-v-h** [comment]
Deploy this instance over https-s3 proxy https://staff.equinixmetal.net/instances/32a688c7-62f7-4280-bf35-07086b6f3483/overview

**Comment by mmlb** [comment]
Re worked in #231

**Pull request closed without merging**
