### PR TITLE
pip install packet-hardware and packet-networking

### PR DESCRIPTION
**Pull request by mikemrm**
## Description

Switch to using packethost/packet-hardware and packet-networking repo instead of code being within project.

Also removed legacy network tests as those test are now handled within the packet-networking repo

## Why is this needed

This allows for easier development of the tools and is able to be used in more ways.

### CODE REVIEW

**Review by gianarb — DISMISSED** [review]

**Comment by mmlb** [comment]
@mikemrm PR title and comment needs updating

**Review by mmlb — COMMENTED** [review]
PR title and body needs updating. Mergify will use those for the merge message so should be kept up2date.

**Review by mmlb — CHANGES_REQUESTED** [review]
gah, I need some  coffee

**Review by mmlb — APPROVED** [review]

**Comment by mmlb** [comment]
We could probably slim down the `ci/Dockerfile` image now a bit too. I know we don't need lshw in there anymore, but fine to leave for now.

**Pull request merged**
