### PR TITLE
alpine: Upgrade alpine linux to 3.14

### PR DESCRIPTION
**Pull request by splaspood**
## Description

Upgrades the alpine linux environment from v3.12 to v3.14.

## Why is this needed

Alpine 3.14 ships docker 20.10 which includes support for multiple log drivers which we need to send log output to a centralized syslog while still allowing 'docker logs' to work.

### CODE REVIEW

**Review by tstromberg — APPROVED** [review]

**Review by tstromberg — CHANGES_REQUESTED** [review]
Saw this error:

```
+ make V=1 T=1 build/discover-metal-x86_64.tar.gz
make: *** No rule to make target 'build/discover-metal-x86_64.tar.gz'.  Stop.
```

@ScottGarman - is this possibly due to Drone restarts?

**Comment by ScottGarman** [comment]
> Saw this error:
> 
> ```
> + make V=1 T=1 build/discover-metal-x86_64.tar.gz
> make: *** No rule to make target 'build/discover-metal-x86_64.tar.gz'.  Stop.
> ```
> 
> @ScottGarman - is this possibly due to Drone restarts?

I'm not sure what is causing this, but something is completely out of whack when we see this. I restarted the drone build, and this time the step worked (and it looked like all it did was pull the discovery container image from quay).

**Comment by ScottGarman** [comment]
This is probably just due to a lack of context on my part, but since we assume to use a specific kernel and linux-firmware package version later on this Dockerfile, shouldn't those also be updated? I assume alpine 3.12 and .14 use different kernel versions.

I tried just building this docker image to experiment, and I am getting an error when I update the alpine version to 3.14:

```
Step 12/23 : RUN cd aports/main/linux-firmware &&     abuild checksum &&     MAKEFLAGS=-j$(nproc) abuild -r &&     abuild clean &&     sudo apk add --no-scripts --no-cache --update --upgrade --cache-dir /tmp/non-persisted-apk-cache-dir         /home/builder/packages/main/x86_64/linux-firmware*.apk
 ---> Running in e552282d2ea9
>>> linux-firmware: Fetching https://dev.alpinelinux.org/archive/linux-firmware/linux-firmware-20200519.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  223M  100  223M    0     0  9558k      0  0:00:23  0:00:23 --:--:-- 12.8M
>>> linux-firmware: Fetching https://community.cypress.com/servlet/JiveServlet/download/19375-1-53475/cypress-fmac-v5.4.18-2020_0402.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
>>> ERROR: linux-firmware: checksum failed
The command '/bin/sh -c cd aports/main/linux-firmware &&     abuild checksum &&     MAKEFLAGS=-j$(nproc) abuild -r &&     abuild clean &&     sudo apk add --no-scripts --no-cache --update --upgrade --cache-dir /tmp/non-persisted-apk-cache-dir         /home/builder/packages/main/x86_64/linux-firmware*.apk' returned a non-zero code: 1
```
The previous version (what we have in main currently). Still builds fine.

Another complicating factor we need to account for is the incoming work to build the ASRock BIOS kernel module that a WIP in PR#284.

**Comment by splaspood** [comment]
Yup, this PR is far from complete, I will need to update the kernel etc.

**Review by mmlb — COMMENTED** [review]
I also update the init script file when alpine is updated so that we get any updates/fixes. I go and find the right commit/tag in https://gitlab.alpinelinux.org/alpine/mkinitfs/-/blob/master/initramfs-init.in at the right tag and replace the `@`'d version with the correct value, `shfmt` it and then save it as init-vanilla-$version. Then I'd go and add all the things we want (diff -u init-vanilla-3.12 init-x86_64 or go through some of the steps in https://github.com/tinkerbell/osie/pull/72/commits)

**Comment by tstromberg** [comment]
Looks good to me - tagging @ScottGarman in just to make sure this doesn't conflict inappropriately with https://github.com/tinkerbell/osie/pull/293

**Comment by ScottGarman** [comment]
You'll definitely want to rebase this against the PR I just merged, which updates the eclypsium driver and userspace app.

However, the main blocker we should consider for this is that we need the new asrock kernel module to build for alpine 3.14, and we don't have that yet. So please don't merge this until we have that situation sorted out, otherwise we'll be blocking a major effort to track BIOS features.

**Comment by nshalman** [comment]
Is this PR going to land before or after the deprecation of this repo?

**Comment by ScottGarman** [comment]
This is still blocked by the fact that the ASRockRack kernel module doesn't yet build for alpine-3.14, so I believe this PR is stalled out. @splaspood can you re-target this appropriately and close this PR?

**Pull request closed without merging**
