### PR TITLE
ensure linux sees all physical drives connected to marvell controller upon reset

### PR DESCRIPTION
**Pull request by mikemrm**
## Description

After clearing the Marvell raid configuration, some time is needed for
the individual drives to register again in linux.

By not waiting, during a deprovision, we may not discover all the
necessary drive to wipe or a wipe may start before the drives are
available to the os.

### CODE REVIEW

**Comment by ScottGarman** [comment]
Have you been able to test this as a custom osie and see it loop and recover?

**Comment by mikemrm** [comment]
During testing I've seen the code which causes it to loop work correctly, however the way it was looking for serials was not working as expected which is why it loop. Since getting the serials the way it's done now, it has not needed to loop as the mvcli command has been slow enough to return that by the time it's completed the disks are available to the os.

Here is output from the SOL

```shell
++ mvcli info -o pd
++ awk '/Serial:/ { print $NF }'
+ pd_serials='203329F89422
203329F893F9'
+ udevadm settle
+ pd_missing=true
+ true
+ sleep 1
+ pd_missing=false
+ echo 'Marvell-Reset: Checking for drives...'
Marvell-Reset: Checking for drives...
+ for serial in '$pd_serials'
+ grep -q 203329F89422 /sys/class/block/sda/device/wwid /sys/class/block/sdb/device/wwid
+ for serial in '$pd_serials'
+ grep -q 203329F893F9 /sys/class/block/sda/device/wwid /sys/class/block/sdb/device/wwid
+ false
```

**Comment by mmlb** [comment]
I wonder if this would apply to other raid cards too?

**Comment by mikemrm** [comment]
> I wonder if this would apply to other raid cards too?

Wouldn't surprise me

**Review by ScottGarman — APPROVED** [review]

**Pull request merged**
