### PR TITLE
Remove c3.medium from chroot_install

### PR DESCRIPTION
**Pull request by dustinmiller**
- [ ] Changelog updated

### CODE REVIEW

**Comment by dustinmiller** [comment]
I don't think was doing much, but since it's not doing anything we should remove it?

**Comment by ScottGarman** [comment]
My understanding is that this got lost during a prior migration of the repo. I'm :+1: on it, but not confident enough about the implications of this that I'll wait for Manny, David, or someone else to do a final review/merge.

**Review by mmlb — CHANGES_REQUESTED** [review]
see commit comment

**Comment by dustinmiller** [comment]
Looks like this was doing stuff and needs removed, updated commit description per @mmlb's request

**Comment by dustinmiller** [comment]
Updated again, should be more descriptive

**Comment by mmlb** [comment]
Thats the stuff!

**Review by mmlb — APPROVED** [review]

**Pull request merged**
