### PR TITLE
correct intel blocksize 

### PR DESCRIPTION
**Pull request by mikemrm**
Intel forgot how to count, this corrects those block sizes

### CODE REVIEW

**Review by benr — DISMISSED** [review]

**Review by dustinmiller — DISMISSED** [review]
Amazing

**Review by dlaube — DISMISSED** [review]

**Review by dlaube — APPROVED** [review]

**Comment by mmlb** [comment]
@mikemrm: wat? `flabs` vs `flbas`?

**Comment by mikemrm** [comment]
> @mikemrm: wat? `flabs` vs `flbas`?

😬  prs welcome :)

**Comment by dustinmiller** [comment]
:laughing: whoops :grimacing:

**Pull request merged**
