### PR TITLE
Run grub stuff from chroot

### PR DESCRIPTION
**Pull request by mmlb**
## Why is this needed

Fixes: #

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by tstromberg** [comment]
@mmlb - Is this PR still being worked on? Do you need any help to move this forward?

**Comment by mmlb** [comment]
Nope not being worked on atm, we can close and I'll re-open if/when I dust it off. Alternatively, happy to have anyone else pick it up :D.

**Comment by mmlb** [comment]
Which actually would be a little difficult as I think this is stuck waiting on useful image in github.com/packethost/packet-images that we can test with.

**Comment by mmlb** [comment]
@sfunkhouser has been working on the image build pipelines

**Comment by mmlb** [comment]
Oops I closed this by mistake somehow.

**Comment by jacobweinstock** [comment]
Hey @mmlb, is this still something you're working on? If so, maybe we put a help-wanted label on it?

**Comment by Raj-Dharwadkar** [comment]
@mmlb, I see this is in draft for a long time. Please can you take look at this PR and update it?

**Pull request closed without merging**
