### PR TITLE
Add Ubuntu 20.04 GRUB templates

### PR DESCRIPTION
**Pull request by dustinmiller**
- [x] Changelog updated

### CODE REVIEW

**Comment by ScottGarman** [comment]
:+1:  for obvious reasons I haven't scoured every line of every file, but the general gist of this looks sane and I assume if something isn't working this is a good base to make fixes from.

**Review by ScottGarman — DISMISSED** [review]

**Comment by ScottGarman** [comment]
:+1: on the rebase.

**Review by ScottGarman — APPROVED** [review]

**Comment by dustinmiller** [comment]
I clicked merged, it appears half merged, awesome, thanks Github

**Comment by dustinmiller** [comment]
This was merged in, Github didn't recognize it here unfortunately.

**Pull request closed without merging**
